#!/bin/bash
#SBATCH -J d2_metric
#SBATCH -p bme_gpu
#SBATCH --time=3000
#SBATCH -N 1
#SBATCH -n 6
#SBATCH --mem 50g
#SBATCH --gres=gpu:1

#SBATCH -o d2m_%j_stdout.log
#SBATCH -e d2m_x_%j_stderr.log

echo ${SLURM_JOB_NODELIST}
echo start on $(date)
# module load apps/fsl/6.0
# module load apps/ants
#. ${FSLDIR}/etc/fslconf/fsl.sh
# conda activate mri
module load 7/compiler/cuda/11.0
cd /hpc/data/home/bme/v-gujch/work/AD_GAN
python healthy_clf.py delta2

echo end on $(date)
