#!/bin/bash
#SBATCH -J generate_delta
#SBATCH -p bme_gpu
#SBATCH --time=400
#SBATCH -N 1
#SBATCH -n 20
#SBATCH --mem 50g
#SBATCH --gres=gpu:1

#SBATCH -o %j_stdout.log
#SBATCH -e %j_stderr.log

echo ${SLURM_JOB_NODELIST}
echo start on $(date)

# module load apps/fsl/6.0
# module load apps/ants
#. ${FSLDIR}/etc/fslconf/fsl.sh
module load 7/compiler/cuda/11.0
cd /hpc/data/home/bme/v-gujch/work/AD_GAN
python generate_delta.py

echo end on $(date)
