#!/bin/bash
#SBATCH -J clf_64x
#SBATCH -p bme_gpu
#SBATCH --time=3000
#SBATCH -N 1
#SBATCH -n 20
#SBATCH --mem 50g
#SBATCH --gres=gpu:1

#SBATCH -o clf_64x_%j_stdout.log
#SBATCH -e clf_64x_%j_stderr.log

echo ${SLURM_JOB_NODELIST}
echo start on $(date)
# module load apps/fsl/6.0
# module load apps/ants
#. ${FSLDIR}/etc/fslconf/fsl.sh
# conda activate mri
module load 7/compiler/cuda/11.0
cd /hpc/data/home/bme/v-gujch/work/AD_GAN
python train_clf_64x.py

echo end on $(date)
