#!/bin/bash
#SBATCH -J health_gan
#SBATCH -p bme_gpu
#SBATCH --time=3000
#SBATCH -N 1
#SBATCH -n 20
#SBATCH --mem 50g
#SBATCH --gres=gpu:1

#SBATCH -o %j_stdout.log
#SBATCH -e %j_stderr.log

echo ${SLURM_JOB_NODELIST}
echo start on $(date)
# module load apps/fsl/6.0
# module load apps/ants
#. ${FSLDIR}/etc/fslconf/fsl.sh
# conda activate mri
module load 7/compiler/cuda/11.4
cd /hpc/data/home/bme/v-gujch/work/AD_GAN
python train_GAN_healthy.py -l 20

echo end on $(date)
