#!/bin/bash
#SBATCH -J pre_t2
#SBATCH -p bme_cpu
#SBATCH --time=200
#SBATCH --mem=100G
#SBATCH -N 1
#SBATCH -n 47

#SBATCH -o %j_stdout.log
#SBATCH -e %j_stderr.log

echo ${SLURM_JOB_NODELIST}
echo start on $(date)

module load apps/fsl/6.0
module load apps/ants
. ${FSLDIR}/etc/fslconf/fsl.sh
# conda activate mri
python ~/work/AD_GAN/pre_procession/prep_T2_multi_processor.py 

echo end on $(date)
