#!/bin/bash
#SBATCH -J ttest
#SBATCH -p bme_cpu
#SBATCH --time=3000
#SBATCH --mem=400G
#SBATCH -N 1
#SBATCH -n 40

#SBATCH -o ttest_%j_stdout.log
#SBATCH -e ttest_%j_stderr.log


echo ${SLURM_JOB_NODELIST}
echo start on $(date)

module load apps/fsl/6.0
. ${FSLDIR}/etc/fslconf/fsl.sh

module load apps/ants
export ANTSPATH=/public/software/apps/ants/bin

# conda activate mri
python ~/work/AD_GAN/analysis/ttest.py 46

echo end on $(date)
